POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "itdev126",
    "password": "1234"
}

### 

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username":"viincyy",
    "password": "1234"
}

###
GET http://localhost:5000/api/film/series
###
GET http://localhost:5000/api/film/films
###
POST http://localhost:5000/api/film/create
Content-Type: application/json

{
    "title": "The Prestige",
    "description":
      "Two friends and fellow magicians become bitter enemies after a sudden tragedy. As they devote themselves to this rivalry, they make sacrifices that bring them fame but with terrible consequences.",
    "genre": "drama",
    "maturity": "15",
    "type": "films",
    "slug": "the-prestige"
}

###
DELETE http://localhost:5000/api/film/6116289725de8915fc731c4a