POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "itdev126",
    "password": "1234"
}

### 

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username":"viincyy",
    "password": "1234"
}

###
GET http://localhost:5000/api/film/series
###
GET http://localhost:5000/api/film/films
###
POST http://localhost:5000/api/film/create
Content-Type: application/json

{
    "title": "Amanda Knox",
    "description": "Amanda Marie Knox is an American woman who spent almost four years in an Italian prison.",
    "genre": "documentaries",
    "maturity": "12",
    "slug": "amanda-knox"
}

###
DELETE http://localhost:5000/api/film/61162160197a1b0bb87ae75f